### ISSUE TITLE
红米4x，miui9.1会一直dialog提示  正在尝试开启或关闭wifi 

### ISSUE THREAD

**Issue by Eklett** [kongqw/KqwWifiManagerDemo#3]
把WiFiManager.java里面的 `case INACTIVE: // 不活跃的`后面的
```
// 断开连接
int networkId = connectFailureInfo.getNetworkId();
boolean isDisable = wifiManager.disableNetwork(networkId);
boolean isDisconnect = wifiManager.disconnect();
Log.i(TAG, "onReceive: 断开连接  =  " + (isDisable && isDisconnect));
```
去掉就好了

**Comment by kongqw** [comment]
什么异常？打开和关闭WI-FI 有问题吗？

**Comment by Eklett** [comment]
应该是权限问题，连接wifi的时候，如果从一个wifi切换到另一个wifi，就会触发DISCONNECTED 或者 INACTIVE，然后调用wifiManager.disableNetwork(networkId)还是 wifiManager.disconnect()的时候需要打开或关闭wifi的权限，所以会弹dialog，这个权限在miui9.1是每次打开或关闭wifi都要申请的。此时点击授权后就会断开连接disconnect()，但是我切换的wifi可能这时候已经连接成功，然后又会触发上面的代码，导致了切换wifi可能会多次触发上面那段代码， 所以会一直弹dialog，并且断开了连接。
